"""
Unified 50-State Agronomic, Climate, and Cooperative Extension Knowledgebase.
Covers all 50 US States + DC with Land-Grant Universities, Regional Soils, and Cultivars.
"""
import json
from pathlib import Path

STATE_EXTENSIONS_DATA = {
  "AL": {
    "state_name": "Alabama",
    "extension_service": "Alabama Cooperative Extension System (Auburn & Alabama A&M)",
    "dominant_soil": "Decatur Silt Loam & Norfolk Sandy Loam (Deep coastal & limestone soils)",
    "soil_texture": "Red Clay Loam & Coastal Plain Sandy Loam",
    "ph_range": "5.5 - 6.5 (Mildly Acidic)",
    "organic_matter": "Moderate (2.0% - 3.0%)",
    "soil_guidance": "Warm southern soils warm up very early. Amend with organic compost and pine bark to retain moisture through hot July/August periods.",
    "raised_bed_recommendation": "Raised beds with drip irrigation prevent nutrient leaching in sandy coastal soils and aerate heavier inland clay.",
    "regional_cultivars": {"tomato": ["Celebrity", "Better Boy", "Bella Rosa"], "peppers": ["Tabasco", "Sweet Banana", "Cayenne"]},
    "regional_pest_watch": ["Root-knot Nematodes (rotate with marigolds)", "Stink Bugs and Leaf-footed Bugs"]
  },
  "AK": {
    "state_name": "Alaska",
    "extension_service": "UAF Cooperative Extension Service",
    "dominant_soil": "Tanana Silt Loam & Peat Organic Soils",
    "soil_texture": "Subarctic Volcanic Ash & Silt Loam",
    "ph_range": "5.2 - 6.2 (Acidic)",
    "organic_matter": "High (5.0% - 10.0%)",
    "soil_guidance": "Subarctic soils are naturally cold. Utilize raised beds, clear plastic mulch, and hoophouses to warm soil for summer growth.",
    "raised_bed_recommendation": "Raised beds (12-18 inches) or high tunnels are essential to capture extreme summer daylight (19+ hours) and elevate roots above permafrost chill.",
    "regional_cultivars": {"cabbage": ["Megaton", "Early Jersey Wakefield"], "potato": ["Yukon Gold", "Magic Molly"], "berries": ["Lingonberry", "Cloudberry"]},
    "regional_pest_watch": ["Root Maggots on Brassicas", "Slugs in coastal maritime regions"]
  },
  "AZ": {
    "state_name": "Arizona",
    "extension_service": "University of Arizona Cooperative Extension",
    "dominant_soil": "Casa Grande Loam & Caliche Aridisols",
    "soil_texture": "Sandy Clay Loam with subsurface Caliche (calcium carbonate)",
    "ph_range": "7.5 - 8.5 (Alkaline)",
    "organic_matter": "Low (0.5% - 1.5%)",
    "soil_guidance": "High desert alkaline soils benefit from heavy organic matter, sulfur amendments, and shade cloth (30-50%) during extreme summer months.",
    "raised_bed_recommendation": "Raised beds filled with imported potting soil and worm castings protect plants from impenetrable caliche layers.",
    "regional_cultivars": {"tomato": ["Heatwave II", "Solar Fire", "Sun Gold"], "peppers": ["Chiltepin", "Poblano", "Anaheim"]},
    "regional_pest_watch": ["Spider Mites during dry heat spells", "Whiteflies and Tomato Psyllids"]
  },
  "AR": {
    "state_name": "Arkansas",
    "extension_service": "University of Arkansas System Division of Agriculture",
    "dominant_soil": "Stuttgart Silt Loam (Ozark Loams & Delta Alluvium)",
    "soil_texture": "Fertile River Delta Silt Loam & Ozark Stony Loam",
    "ph_range": "5.8 - 6.8 (Moderately Acidic to Neutral)",
    "organic_matter": "Moderate (2.5% - 3.8%)",
    "soil_guidance": "Arkansas delta soils are naturally nutrient-dense. Upland Ozark soils benefit from organic mulch to buffer rocky slopes.",
    "raised_bed_recommendation": "Raised beds warm quickly for early spring greens and provide reliable drainage in wet spring seasons.",
    "regional_cultivars": {"tomato": ["Bradley Pink (AR Heritage)", "Mountain Spring"], "berries": ["Ouachita Blackberry", "Natchez"]},
    "regional_pest_watch": ["Squash Bugs", "Blossom End Rot (maintain consistent deep watering)"]
  },
  "CA": {
    "state_name": "California",
    "extension_service": "UC Agriculture and Natural Resources (UC Master Gardeners)",
    "dominant_soil": "San Joaquin Loam & Valley Alluvial Soil",
    "soil_texture": "Deep Sandy Loam, Clay Loam & Adobe Clay",
    "ph_range": "6.2 - 7.5 (Balanced to slightly alkaline)",
    "organic_matter": "Moderate (2.0% - 3.5%)",
    "soil_guidance": "Mediterranean climate allows year-round gardening. Drip irrigation and thick wood mulch are critical for summer water conservation.",
    "raised_bed_recommendation": "Raised beds with drip emitters maximize vegetable yields while reducing irrigation water usage by up to 60%.",
    "regional_cultivars": {"tomato": ["Early Girl", "San Marzano", "Cherokee Purple"], "peppers": ["Padron", "Serrano", "Bell"]},
    "regional_pest_watch": ["Citrus Leafminer", "Tomato Hornworm", "Aphids on spring brassicas"]
  },
  "CO": {
    "state_name": "Colorado",
    "extension_service": "Colorado State University Extension",
    "dominant_soil": "Fort Collins Loam & Sandy Clay Loam (High Plains Mollisols)",
    "soil_texture": "Clay Loam with high mineral content",
    "ph_range": "7.0 - 8.0 (Alkaline)",
    "organic_matter": "Low to Moderate (1.5% - 2.5%)",
    "soil_guidance": "Intense high-altitude UV and dry winds dry soil quickly. Heavy compost incorporation helps buffer alkaline pH.",
    "raised_bed_recommendation": "Raised beds warm quickly in May at high elevations (5000ft+) and help protect plants from unseasonal late spring freezes.",
    "regional_cultivars": {"tomato": ["Stupice (Cold Hardy)", "Sub-Arctic Plenty", "Celebrity"], "peppers": ["Pueblo Chile", "Mirassol"]},
    "regional_pest_watch": ["Flea Beetles on young seedlings", "Grasshoppers in mid-summer"]
  },
  "CT": {
    "state_name": "Connecticut",
    "extension_service": "UConn Extension",
    "dominant_soil": "Windsor Loamy Sand & Charlton-Chatfield Loam",
    "soil_texture": "Fine Sandy Loam & Glacial Till",
    "ph_range": "5.5 - 6.5 (Acidic)",
    "organic_matter": "Moderate (3.0% - 4.5%)",
    "soil_guidance": "Glacial till soils have good structure but benefit from lime to raise native acidity for brassicas and nightshades.",
    "raised_bed_recommendation": "Raised beds with dark organic compost absorb spring sunlight and bypass rocky New England subsoil.",
    "regional_cultivars": {"tomato": ["New England Heirloom", "Brandywine", "Jet Star"], "squash": ["Waltham Butternut", "Delicata"]},
    "regional_pest_watch": ["Squash Vine Borer", "Striped Cucumber Beetle"]
  },
  "DE": {
    "state_name": "Delaware",
    "extension_service": "University of Delaware Cooperative Extension",
    "dominant_soil": "Greenwich Silt Loam & Coastal Plain Sand",
    "soil_texture": "Light Silt Loam over Sandy Marine Sediments",
    "ph_range": "5.6 - 6.5 (Mildly Acidic)",
    "organic_matter": "Moderate (2.0% - 3.2%)",
    "soil_guidance": "Coastal plain soils drain rapidly and warm up in mid-April. Regular compost additions maintain steady soil moisture.",
    "raised_bed_recommendation": "Raised beds with leaf mold compost keep root vegetables loose, straight, and well-aerated.",
    "regional_cultivars": {"tomato": ["Celebrity", "Rutgers", "Sun Gold"], "watermelon": ["Crimson Sweet", "Sugar Baby"]},
    "regional_pest_watch": ["Harlequin Bugs", "Corn Earworm in sweet corn and tomatoes"]
  },
  "DC": {
    "state_name": "District of Columbia",
    "extension_service": "UDC Center for Urban Agriculture & Gardening",
    "dominant_soil": "Urban Silt Loam & Potomac River Alluvium",
    "soil_texture": "Urban Disturbed Loam & River Sand",
    "ph_range": "6.2 - 7.0 (Near Neutral)",
    "organic_matter": "Moderate (3.0% - 4.0%)",
    "soil_guidance": "Urban soils should be tested or cultivated in raised beds/planters with clean potting blends to ensure healthy organic growing.",
    "raised_bed_recommendation": "Raised beds (12+ inches) and rooftop/patio containers are ideal for compact urban gardening and maximizing sunlight.",
    "regional_cultivars": {"tomato": ["Patio Choice", "Sweet 'N' Neat", "Cherokee Purple"], "herbs": ["Genovese Basil", "Cilantro"]},
    "regional_pest_watch": ["Cabbage Loopers", "Whiteflies in enclosed courtyard gardens"]
  },
  "FL": {
    "state_name": "Florida",
    "extension_service": "University of Florida IFAS Extension",
    "dominant_soil": "Myakka Fine Sand (Florida State Soil)",
    "soil_texture": "Rapidly Draining Sandy Soil",
    "ph_range": "5.0 - 6.5 (Acidic to Neutral)",
    "organic_matter": "Low (1.0% - 2.0%)",
    "soil_guidance": "Florida has a reversed growing season (Fall/Winter/Spring are primary). Heavy summer heat and rains cause root rot; plant warm vegetables in autumn.",
    "raised_bed_recommendation": "Raised beds filled with rich compost and coconut coir are essential to prevent fast nutrient leaching in Florida's porous sand.",
    "regional_cultivars": {"tomato": ["Solar Fire", "Florida 91", "Everglades Currant"], "peppers": ["Datil (FL Heritage)", "Seminole Pumpkin"]},
    "regional_pest_watch": ["Root-knot Nematodes", "Whiteflies and Papaya Fruit Fly"]
  },
  "GA": {
    "state_name": "Georgia",
    "extension_service": "University of Georgia Extension",
    "dominant_soil": "Tifton Urban Silt Loam & Georgia Red Clay (Piedmont Ultisols)",
    "soil_texture": "Dense Red Clay & Coastal Plain Sandy Loam",
    "ph_range": "5.2 - 6.2 (Acidic)",
    "organic_matter": "Moderate (2.0% - 3.2%)",
    "soil_guidance": "Georgia red clay is rich in minerals but compacts easily under downpours. Incorporate coarse compost and pine fines.",
    "raised_bed_recommendation": "Raised beds (8-12 inches) improve root aeration and drainage in heavy red clay, preventing root suffocation.",
    "regional_cultivars": {"tomato": ["Amelia", "Mountain Pride", "Cherokee Purple"], "greens": ["Georgia Southern Collards", "Vidalia Onion"]},
    "regional_pest_watch": ["Tomato Fruitworm", "Southern Blight (Sclerotium rolfsii)"]
  },
  "HI": {
    "state_name": "Hawaii",
    "extension_service": "UH CTAHR Cooperative Extension",
    "dominant_soil": "Kokee Volcanic Ash & Oxisols (Tropical Red Soils)",
    "soil_texture": "Rich Volcanic Clay Loam & Basaltic Soils",
    "ph_range": "5.5 - 6.8 (Mildly Acidic)",
    "organic_matter": "High (4.0% - 8.0%)",
    "soil_guidance": "Year-round tropical growing season. High humidity requires wide plant spacing for airflow and organic slug control.",
    "raised_bed_recommendation": "Raised beds with volcanic cinder amendments ensure superior aeration and drain tropical deluge rains effortlessly.",
    "regional_cultivars": {"tomato": ["Anahu (UH Nematode Resistant)", "Kewalo"], "greens": ["Okinawa Spinach", "Hawaiian Chili Pepper"]},
    "regional_pest_watch": ["Melon Fly (Bactrocera cucurbitae)", "Oriental Fruit Fly"]
  },
  "ID": {
    "state_name": "Idaho",
    "extension_service": "University of Idaho Extension",
    "dominant_soil": "Threebear Silt Loam & Snake River Valley Volcanic Loams",
    "soil_texture": "Volcanic Silt Loam & Fine Sandy Loam",
    "ph_range": "6.5 - 7.8 (Near Neutral to Alkaline)",
    "organic_matter": "Moderate (2.5% - 4.0%)",
    "soil_guidance": "Rich volcanic ash soils provide exceptional mineral fertility. Protect early spring transplants from mountain night chills.",
    "raised_bed_recommendation": "Raised beds elevate soil temps rapidly in spring and accommodate deep potato and root development.",
    "regional_cultivars": {"potato": ["Russet Burbank", "Idaho Fingerling"], "tomato": ["Ida Gold", "Sub-Arctic Plenty", "Glacier"]},
    "regional_pest_watch": ["Colorado Potato Beetle", "Wireworms in early spring"]
  },
  "IL": {
    "state_name": "Illinois",
    "extension_service": "University of Illinois Extension",
    "dominant_soil": "Drummer Silty Clay Loam & Flanagan Silt Loam (Prairie Mollisols)",
    "soil_texture": "Deep Fertile Black Prairie Loam",
    "ph_range": "6.2 - 6.8 (Optimal neutral)",
    "organic_matter": "Very High (4.5% - 6.0%)",
    "soil_guidance": "World-class natural soil quality with huge natural nutrient storage. Focus on maintaining loose aeration with finished compost.",
    "raised_bed_recommendation": "Raised beds warm up 2 weeks faster in April and prevent spring waterlogging for tomatoes and bell peppers.",
    "regional_cultivars": {"tomato": ["Early Girl", "Supersonic", "Cherokee Purple", "Sweet 100"], "sweet_corn": ["Silver Queen", "Incredible"]},
    "regional_pest_watch": ["Squash Vine Borer (late June)", "Early Blight on lower nightshade leaves"]
  },
  "IN": {
    "state_name": "Indiana",
    "extension_service": "Purdue University Extension",
    "dominant_soil": "Miami Silt Loam (Glacial Till & Loess)",
    "soil_texture": "Fertile Silt Loam with moderate clay subsoil",
    "ph_range": "6.0 - 6.8 (Neutral)",
    "organic_matter": "High (3.5% - 4.8%)",
    "soil_guidance": "Deep Midwest glacial soils produce stellar vegetables. Light organic mulching keeps tomatoes weed-free and cool in July.",
    "raised_bed_recommendation": "Raised beds or mounded rows provide ideal drainage during wet Midwestern Aprils.",
    "regional_cultivars": {"tomato": ["Indiana Red", "Big Boy", "Mountain Fresh Plus"], "melon": ["Athena Cantaloupe", "Sweet Slice"]},
    "regional_pest_watch": ["Japanese Beetles", "Cucumber Beetles transmitting bacterial wilt"]
  },
  "IA": {
    "state_name": "Iowa",
    "extension_service": "Iowa State University Extension and Outreach",
    "dominant_soil": "Tama Silt Loam (Rich Loess Prairie Topsoil)",
    "soil_texture": "Deep Organic Silt Loam",
    "ph_range": "6.2 - 7.0 (Near Neutral)",
    "organic_matter": "Extremely High (5.0% - 7.0%)",
    "soil_guidance": "Among the most fertile agricultural soils on Earth. Generous organic matter supports continuous heavy-feeding vegetables.",
    "raised_bed_recommendation": "In-ground beds produce astonishing yields; raised beds are perfect for early spring greens and strawberries.",
    "regional_cultivars": {"tomato": ["Iowa Heirloom", "Beefsteak", "Amish Paste"], "beans": ["Provider", "Blue Lake Bush"]},
    "regional_pest_watch": ["Corn Earworm", "Tomato Hornworm in late summer"]
  },
  "KS": {
    "state_name": "Kansas",
    "extension_service": "K-State Research and Extension",
    "dominant_soil": "Harney Silt Loam (Kansas State Soil - Loess Mollisols)",
    "soil_texture": "Heavy Silt Loam & Prairie Loam",
    "ph_range": "6.5 - 7.5 (Balanced)",
    "organic_matter": "High (3.0% - 4.5%)",
    "soil_guidance": "Hot prairie summer winds require sturdy trellises and 3-inch straw mulch to conserve root moisture.",
    "raised_bed_recommendation": "Raised beds with windbreak cloth yield outstanding early tomatoes and crisp peppers.",
    "regional_cultivars": {"tomato": ["Celebrity", "Jet Star", "Early Girl"], "sunflower": ["Autumn Beauty", "Mammoth Russian"]},
    "regional_pest_watch": ["Grasshoppers in late July", "Squash Bugs"]
  },
  "KY": {
    "state_name": "Kentucky",
    "extension_service": "University of Kentucky Cooperative Extension",
    "dominant_soil": "Crider Silt Loam (Limestone-derived Loess)",
    "soil_texture": "Deep Silt Loam with limestone subsoil",
    "ph_range": "5.8 - 6.8 (Limestone buffered)",
    "organic_matter": "Moderate to High (3.0% - 4.2%)",
    "soil_guidance": "Bluegrass region limestone buffering delivers great calcium levels, naturally preventing tomato blossom end rot.",
    "raised_bed_recommendation": "Raised beds along rolling terrain prevent runoff and create deep, loose root zones for carrots and garlic.",
    "regional_cultivars": {"tomato": ["Kentucky Beefsteak (Heirloom)", "German Queen", "Better Boy"], "beans": ["Kentucky Wonder Pole"]},
    "regional_pest_watch": ["Flea Beetles on eggplants", "Stinkbugs on ripening fruit"]
  },
  "LA": {
    "state_name": "Louisiana",
    "extension_service": "LSU AgCenter",
    "dominant_soil": "Ruston Fine Sandy Loam & Mississippi Alluvial Silt",
    "soil_texture": "Rich Alluvial Silt Loam & Coastal Sandy Loam",
    "ph_range": "5.2 - 6.5 (Acidic to Neutral)",
    "organic_matter": "Moderate (2.5% - 3.8%)",
    "soil_guidance": "Long humid growing season supports early spring and robust autumn/winter vegetable gardens.",
    "raised_bed_recommendation": "Raised beds (12 inches high) are essential to maintain drainage above high coastal water tables during Gulf storms.",
    "regional_cultivars": {"okra": ["Louisiana Green Velvet", "Clemson Spineless"], "tomato": ["Creole (LA Heritage)", "Bella Rosa"], "peppers": ["Tabasco", "Cayenne"]},
    "regional_pest_watch": ["Armyworms", "Root-knot Nematodes", "Fungal Powdery Mildew"]
  },
  "ME": {
    "state_name": "Maine",
    "extension_service": "University of Maine Cooperative Extension",
    "dominant_soil": "Chesuncook Silt Loam & Glacial Till",
    "soil_texture": "Rocky Silt Loam & Fine Sandy Loam",
    "ph_range": "4.8 - 5.8 (Strongly Acidic)",
    "organic_matter": "High (4.0% - 6.0%)",
    "soil_guidance": "Short northern growing season. Add dolomitic limestone to raise pH and use black landscape fabric to capture spring soil warmth.",
    "raised_bed_recommendation": "Raised beds filled with composted manure and peat warm up weeks before frozen ground thaws in spring.",
    "regional_cultivars": {"potato": ["Kennebec", "Katahdin", "Yukon Gold"], "berries": ["Wild Maine Blueberry", "Latham Raspberry"], "tomato": ["Glacier", "Moskvich"]},
    "regional_pest_watch": ["Colorado Potato Beetle", "Late Blight in wet coastal Augusts"]
  },
  "MD": {
    "state_name": "Maryland",
    "extension_service": "University of Maryland Extension (Home & Garden Info Center)",
    "dominant_soil": "Sassafras Sandy Loam (Chesapeake Coastal Plain)",
    "soil_texture": "Fine Sandy Loam over silty clay subsoil",
    "ph_range": "5.6 - 6.6 (Mildly Acidic)",
    "organic_matter": "Moderate (2.5% - 3.5%)",
    "soil_guidance": "Chesapeake marine climate buffers spring frost. Incorporate leaf compost to improve moisture holding in sandy loam.",
    "raised_bed_recommendation": "Raised beds with a 50/50 loam-compost blend prevent soil compaction and yield abundant peppers and greens.",
    "regional_cultivars": {"tomato": ["Rutgers", "Cherokee Purple", "Sun Gold"], "melon": ["Eastern Shipper Cantaloupe", "Sugar Baby"]},
    "regional_pest_watch": ["Harlequin Bugs on kale", "Brown Marmorated Stink Bug"]
  },
  "MA": {
    "state_name": "Massachusetts",
    "extension_service": "UMass Extension Vegetable Program",
    "dominant_soil": "Paxton Fine Sandy Loam (Glacial Drumlin Till)",
    "soil_texture": "Sandy Loam with glacial stones",
    "ph_range": "5.2 - 6.2 (Acidic)",
    "organic_matter": "Moderate to High (3.5% - 5.0%)",
    "soil_guidance": "New England rocky soils benefit from stone removal and garden lime amendments to optimize brassica and nightshade health.",
    "raised_bed_recommendation": "Raised wooden beds bypass rocky subsoil and capture intense mid-summer sunlight for sweet tomatoes.",
    "regional_cultivars": {"tomato": ["Brandywine", "Pruden's Purple", "Jet Star"], "squash": ["Waltham Butternut (MA Origin)", "Boston Marrow"]},
    "regional_pest_watch": ["Striped Cucumber Beetle", "Squash Vine Borer"]
  },
  "MI": {
    "state_name": "Michigan",
    "extension_service": "Michigan State University (MSU) Extension",
    "dominant_soil": "Kalkaska Sand & Miami Loam (Glacial Lake Plain Soils)",
    "soil_texture": "Sandy Loam & Rich Lakebed Silt Loam",
    "ph_range": "5.8 - 6.8 (Neutral)",
    "organic_matter": "High (3.5% - 5.5%)",
    "soil_guidance": "Great Lakes water buffers temperature extremes along the coastline. Sandy soils require regular organic compost additions.",
    "raised_bed_recommendation": "Raised beds warm early in May, supporting long-season heirloom tomatoes and crisp pickling cucumbers.",
    "regional_cultivars": {"cucumber": ["National Pickling (MSU Origin)", "Marketmore"], "tomato": ["Early Girl", "Cherokee Purple"], "berries": ["Bluecrop Blueberry"]},
    "regional_pest_watch": ["Spotted Wing Drosophila in soft berries", "Hornworms in late July"]
  },
  "MN": {
    "state_name": "Minnesota",
    "extension_service": "University of Minnesota Extension",
    "dominant_soil": "Lester Loam (Glacial Till Prairie Soil)",
    "soil_texture": "Deep Fertile Loam with rich humus",
    "ph_range": "6.0 - 7.0 (Neutral)",
    "organic_matter": "Very High (4.5% - 6.5%)",
    "soil_guidance": "Intense summer sun and rich topsoil allow ultra-fast vegetable growth during the crisp 140-day frost-free window.",
    "raised_bed_recommendation": "Raised beds covered with clear plastic in late April thaw frozen ground 2-3 weeks ahead of schedule.",
    "regional_cultivars": {"apple": ["Honeycrisp (UMinn Origin)", "Zestar!"], "tomato": ["Northern Lights", "Siberian", "Stupice"], "squash": ["Buttercup", "Delicata"]},
    "regional_pest_watch": ["Flea Beetles in May", "Squash Bugs in mid-summer"]
  },
  "MS": {
    "state_name": "Mississippi",
    "extension_service": "Mississippi State University Extension Service",
    "dominant_soil": "Natchez Silt Loam & Mississippi Delta Alluvium",
    "soil_texture": "Heavy Alluvial Silt & Coastal Pine Sandy Loam",
    "ph_range": "5.2 - 6.4 (Acidic)",
    "organic_matter": "Moderate (2.0% - 3.2%)",
    "soil_guidance": "Long hot growing season with abundant rainfall. Heavy pine straw mulching keeps root temperatures down during August heat.",
    "raised_bed_recommendation": "Raised beds ensure oxygen reaches plant roots during heavy subtropical rainstorms.",
    "regional_cultivars": {"okra": ["Clemson Spineless", "Burgundy"], "sweet_potato": ["Beauregard (High Yield)", "Covington"], "tomato": ["Heatmaster", "Celebrity"]},
    "regional_pest_watch": ["Root-knot Nematodes", "Southern Green Stink Bug"]
  },
  "MO": {
    "state_name": "Missouri",
    "extension_service": "University of Missouri Extension",
    "dominant_soil": "Menfro Silt Loam (Ozark Loams & Missouri River Loess)",
    "soil_texture": "Fertile River Loess & Ozark Gravelly Loam",
    "ph_range": "5.8 - 6.8 (Neutral)",
    "organic_matter": "High (3.2% - 4.5%)",
    "soil_guidance": "Loess river hills provide deep, well-draining soil. Ozark rockier soils require regular compost top-dressing.",
    "raised_bed_recommendation": "Raised beds with a 1/3 compost, 1/3 peat, 1/3 perlite recipe provide effortless root growth and early spring warm-up.",
    "regional_cultivars": {"tomato": ["Missouri Heirloom", "German Pink", "Celebrity"], "peppers": ["Ozark Giant Bell", "Sweet Banana"]},
    "regional_pest_watch": ["Squash Vine Borer", "Blossom End Rot from moisture fluctuation"]
  },
  "MT": {
    "state_name": "Montana",
    "extension_service": "Montana State University Extension",
    "dominant_soil": "Scobey Loam & Glacial Till (Northern Plains Mollisols)",
    "soil_texture": "Clay Loam with high mineral calcium content",
    "ph_range": "6.8 - 7.8 (Slightly Alkaline)",
    "organic_matter": "Moderate (2.0% - 3.5%)",
    "soil_guidance": "Short summer window with cool mountain nights. Select ultra-fast maturity cultivars (50-65 days).",
    "raised_bed_recommendation": "Raised beds equipped with low hoop frost cloth allow continuous vegetable harvesting from May through September.",
    "regional_cultivars": {"tomato": ["Glacier (Cold Setting)", "Stupice", "Sub-Arctic Plenty"], "greens": ["Winterbor Kale", "Spinach"]},
    "regional_pest_watch": ["Flea Beetles on young transplants", "Cutworms in spring"]
  },
  "NE": {
    "state_name": "Nebraska",
    "extension_service": "Nebraska Extension in Lancaster & State Counties",
    "dominant_soil": "Holdrege Silt Loam (Loess Prairie Plains)",
    "soil_texture": "Deep Prairie Silt Loam",
    "ph_range": "6.2 - 7.2 (Near Neutral)",
    "organic_matter": "High (3.5% - 5.0%)",
    "soil_guidance": "Thick loess topsoils have outstanding water-holding capacity. Mulch with clean straw to protect against prairie winds.",
    "raised_bed_recommendation": "Raised beds warm rapidly in May and simplify installation of drip irrigation lines.",
    "regional_cultivars": {"tomato": ["Nebraska Wedding (Heritage Orange)", "Celebrity", "Beefsteak"], "sweet_corn": ["Golden Bantam", "Incredible"]},
    "regional_pest_watch": ["Grasshoppers in late summer", "Tomato Hornworms"]
  },
  "NV": {
    "state_name": "Nevada",
    "extension_service": "University of Nevada, Reno Extension",
    "dominant_soil": "Orovada Fine Sandy Loam (Great Basin Aridisols)",
    "soil_texture": "Alkaline Sandy Loam with desert mineral crust",
    "ph_range": "7.5 - 8.5 (Alkaline)",
    "organic_matter": "Low (0.8% - 1.5%)",
    "soil_guidance": "Desert arid soils require generous peat moss and finished compost amendments to buffer high alkalinity.",
    "raised_bed_recommendation": "Raised garden beds filled with custom potting soil are strongly recommended to bypass native caliche and salty soil.",
    "regional_cultivars": {"tomato": ["Solar Fire", "Early Girl", "Sun Gold"], "peppers": ["Anaheim", "Poblano", "Jalapeño"]},
    "regional_pest_watch": ["Spider Mites during dry heat", "Leafhoppers"]
  },
  "NH": {
    "state_name": "New Hampshire",
    "extension_service": "UNH Cooperative Extension",
    "dominant_soil": "Marlow Fine Sandy Loam (Granite State Glacial Till)",
    "soil_texture": "Granitic Sandy Loam with granite stones",
    "ph_range": "4.8 - 5.8 (Acidic)",
    "organic_matter": "Moderate to High (3.5% - 5.0%)",
    "soil_guidance": "Granite-derived soils are naturally acidic. Apply dolomitic limestone to provide calcium and buffer soil pH.",
    "raised_bed_recommendation": "Raised beds bypass stony granitic subsoil and allow soil to warm 10-15 days earlier in May.",
    "regional_cultivars": {"tomato": ["New Hampshire Victor (UNH Bred)", "Jet Star", "Brandywine"], "squash": ["Waltham Butternut", "Buttercup"]},
    "regional_pest_watch": ["Squash Vine Borer", "Colorado Potato Beetle"]
  },
  "NJ": {
    "state_name": "New Jersey",
    "extension_service": "Rutgers Cooperative Extension (NJAES)",
    "dominant_soil": "Freehold Sandy Loam & Sassafras Loam (Garden State Coastal Plains)",
    "soil_texture": "Fertile Sandy Loam & Silt Loam",
    "ph_range": "5.8 - 6.6 (Near Neutral)",
    "organic_matter": "Moderate to High (3.0% - 4.5%)",
    "soil_guidance": "The Garden State's soils have legendary heirloom vegetable fertility. Light compost topdressing maintains perfect crumb structure.",
    "raised_bed_recommendation": "Raised beds warm in early April for famous Jersey tomatoes, sweet peppers, and continuous eggplant harvests.",
    "regional_cultivars": {"tomato": ["Rutgers 250 (Heritage Classic)", "Ramapo", "Moreton"], "eggplant": ["Black Beauty", "Classic"]},
    "regional_pest_watch": ["Flea Beetles on young eggplants", "Septoria Leaf Spot (mulch under vines)"]
  },
  "NM": {
    "state_name": "New Mexico",
    "extension_service": "NMSU Cooperative Extension Service",
    "dominant_soil": "Penistaja Sandy Loam & Rio Grande Alluvium",
    "soil_texture": "Sandy Loam & Caliche Clay Loam",
    "ph_range": "7.4 - 8.2 (Alkaline)",
    "organic_matter": "Low to Moderate (1.0% - 2.2%)",
    "soil_guidance": "High desert sunshine paired with mineral soils produces world-renowned chiles. Deep compost incorporation is crucial.",
    "raised_bed_recommendation": "Raised beds with automated drip lines retain scarce moisture and protect roots from hot alkaline ground.",
    "regional_cultivars": {"chile": ["Hatch Green Chile (Sandia/Big Jim)", "Chimayó Heirloom", "Barker's Hot"], "tomato": ["Solar Fire", "Celebrity"]},
    "regional_pest_watch": ["Hornworms on chile and tomato vines", "Spider Mites during dry June"]
  },
  "NY": {
    "state_name": "New York",
    "extension_service": "Cornell Cooperative Extension (CCE)",
    "dominant_soil": "Honeoye Silt Loam & Ontario Loam (Finger Lakes Limestone Glacial Till)",
    "soil_texture": "Deep Limestone-buffered Silt Loam & Hudson Valley Alluvium",
    "ph_range": "6.2 - 7.0 (Near Neutral)",
    "organic_matter": "High (3.8% - 5.5%)",
    "soil_guidance": "Naturally fertile limestone soils across upstate NY provide robust natural calcium. Maintain aeration with leaf mold.",
    "raised_bed_recommendation": "Raised beds warm up damp May soil and ensure tomatoes, squash, and sweet corn avoid cold wet spring roots.",
    "regional_cultivars": {"tomato": ["Iron Lady (Cornell Blight Resistant)", "Defiant PhR", "Brandywine"], "apple": ["Empire", "Honeycrisp", "Cortland"]},
    "regional_pest_watch": ["Late Blight (monitor humid August weather)", "Striped Cucumber Beetle"]
  },
  "NC": {
    "state_name": "North Carolina",
    "extension_service": "NC State Extension & NC A&T",
    "dominant_soil": "Cecil Silt Loam (Piedmont Red Clay) & Norfolk Sand",
    "soil_texture": "Heavy Red Clay in Piedmont & Sandy Loam in Coastal Plain",
    "ph_range": "5.2 - 6.2 (Acidic)",
    "organic_matter": "Moderate (2.0% - 3.4%)",
    "soil_guidance": "Piedmont red clay holds great nutrients but needs pine bark fines/compost to prevent hard baking in summer heat.",
    "raised_bed_recommendation": "Raised beds filled with composted pine bark and organic manure prevent clay compaction and improve spring drainage.",
    "regional_cultivars": {"tomato": ["Mountain Pride (NC State Bred)", "Cherokee Purple", "Mountain Fresh"], "sweet_potato": ["Covington (NC Bred Standard)", "Beauregard"]},
    "regional_pest_watch": ["Tomato Spotted Wilt Virus (thrip control)", "Squash Vine Borer"]
  },
  "ND": {
    "state_name": "North Dakota",
    "extension_service": "NDSU Extension",
    "dominant_soil": "Williams Loam & Red River Valley Black Clay",
    "soil_texture": "Dense Black Clay & Glacial Prairie Loam",
    "ph_range": "6.8 - 7.8 (Near Neutral to Alkaline)",
    "organic_matter": "Extremely High (5.5% - 8.0%)",
    "soil_guidance": "Red River Valley soils have astonishing organic depth. Cold winters mean spring soil takes longer to warm without raised beds.",
    "raised_bed_recommendation": "Raised beds (12 inches) with black landscape fabric elevate soil temperatures quickly for short-season northern crops.",
    "regional_cultivars": {"tomato": ["Manitoba", "Sheyenne (NDSU Bred)", "Sub-Arctic Plenty"], "cabbage": ["Late Flat Dutch", "Golden Acre"]},
    "regional_pest_watch": ["Flea Beetles on young seedlings", "Cutworms in May"]
  },
  "OH": {
    "state_name": "Ohio",
    "extension_service": "Ohio State University (OSU) Extension",
    "dominant_soil": "Miamian Silt Loam (Glacial Till & River Loess)",
    "soil_texture": "Fertile Silt Loam with moderate clay subsoil",
    "ph_range": "6.0 - 6.8 (Neutral)",
    "organic_matter": "High (3.5% - 4.8%)",
    "soil_guidance": "Rich Ohio soils produce stellar vegetable gardens. Mulch with straw to protect tomato roots during humid July heat.",
    "raised_bed_recommendation": "Raised beds facilitate early April seed sowing of sugar snap peas, spinach, and crisp radishes.",
    "regional_cultivars": {"tomato": ["Ohio 8245", "Jubilee", "Big Boy", "Cherokee Purple"], "sweet_corn": ["Silver Queen", "Bodacious"]},
    "regional_pest_watch": ["Japanese Beetles in July", "Cucumber Beetles"]
  },
  "OK": {
    "state_name": "Oklahoma",
    "extension_service": "Oklahoma State University (OSU) Extension",
    "dominant_soil": "Port Silt Loam (Red River Basin Alluvial Loam)",
    "soil_texture": "Red Silt Loam & Prairie Sandy Loam",
    "ph_range": "6.0 - 7.2 (Near Neutral)",
    "organic_matter": "Moderate (2.2% - 3.5%)",
    "soil_guidance": "High summer heat (100°F+) halts mid-summer tomato fruit set. Plant early in April or second-crop in August for fall production.",
    "raised_bed_recommendation": "Raised beds paired with 30% shade cloth protect tender vegetables from harsh summer afternoon sun.",
    "regional_cultivars": {"tomato": ["Porter (Drought Hardy Heritage)", "Solar Fire", "Celebrity"], "watermelon": ["Black Diamond", "Crimson Sweet"]},
    "regional_pest_watch": ["Squash Bugs", "Spider Mites during dry summer winds"]
  },
  "OR": {
    "state_name": "Oregon",
    "extension_service": "OSU Extension Service (Oregon State University)",
    "dominant_soil": "Jory Clay Loam (Willamette Valley Volcanic Basalt)",
    "soil_texture": "Rich Red Volcanic Clay Loam & Alluvial Loam",
    "ph_range": "5.4 - 6.2 (Mildly Acidic)",
    "organic_matter": "Very High (4.5% - 7.0%)",
    "soil_guidance": "Pacific Northwest cool maritime spring requires disease-resistant cultivars; summer offers perfect dry, warm ripening days.",
    "raised_bed_recommendation": "Raised beds drain heavy winter/spring rains effortlessly and warm quickly for early seed sowing in March.",
    "regional_cultivars": {"tomato": ["Oregon Spring (OSU Bred)", "Legend (Late Blight Resistant)", "Siletz"], "berries": ["Marionberry", "Hood Strawberry"]},
    "regional_pest_watch": ["Slugs in spring (use organic iron phosphate)", "Late Blight in autumn"]
  },
  "PA": {
    "state_name": "Pennsylvania",
    "extension_service": "Penn State Extension",
    "dominant_soil": "Hazleton Silt Loam & Hagerstown Limestone Loam",
    "soil_texture": "Deep Limestone Silt Loam & Sandstone Uplands",
    "ph_range": "6.0 - 6.8 (Neutral)",
    "organic_matter": "High (3.5% - 5.0%)",
    "soil_guidance": "Lancaster and valley limestone soils offer legendary fertility. Add organic leaf mulch to prevent soil splashing on nightshade leaves.",
    "raised_bed_recommendation": "Raised beds prevent soil compaction in wet springs and support heavy-feeding heirloom tomatoes and sweet corn.",
    "regional_cultivars": {"tomato": ["Penn State Heirloom", "Brandywine (PA Dutch Classic)", "Mountain Fresh"], "peppers": ["Keystone Resistant Giant"]},
    "regional_pest_watch": ["Tomato Hornworm", "Early Blight on lower foliage"]
  },
  "RI": {
    "state_name": "Rhode Island",
    "extension_service": "URI Cooperative Extension",
    "dominant_soil": "Narragansett Silt Loam (Glacial Till & Marine Silt)",
    "soil_texture": "Silt Loam over friable gravelly sand",
    "ph_range": "5.2 - 6.2 (Acidic)",
    "organic_matter": "Moderate to High (3.5% - 4.8%)",
    "soil_guidance": "Narragansett soils have good aggregate structure. Apply dolomitic limestone to provide balanced calcium and magnesium.",
    "raised_bed_recommendation": "Raised beds warm rapidly in May along coastal breezes and prevent root rot in rainy springs.",
    "regional_cultivars": {"tomato": ["Jet Star", "Sun Gold", "Early Girl"], "greens": ["Narragansett Turkey Flint Corn", "Bloomsdale Spinach"]},
    "regional_pest_watch": ["Striped Cucumber Beetle", "Cabbage White Butterfly (caterpillar control)"]
  },
  "SC": {
    "state_name": "South Carolina",
    "extension_service": "Clemson University Cooperative Extension",
    "dominant_soil": "Lynchburg Sandy Loam & Piedmont Red Clay",
    "soil_texture": "Coastal Plain Sand & Piedmont Ultisols",
    "ph_range": "5.4 - 6.4 (Acidic)",
    "organic_matter": "Moderate (2.0% - 3.2%)",
    "soil_guidance": "Hot, humid summers allow two distinct vegetable seasons (Spring and Autumn). Use pine straw mulch to cool soil roots.",
    "raised_bed_recommendation": "Raised beds with composted manure prevent soil compaction and drain heavy tropical afternoon thunderstorms.",
    "regional_cultivars": {"tomato": ["Carolina Gold", "Celebrity", "Cherokee Purple"], "collards": ["Carolina Broadleaf", "Clemson Spineless Okra"]},
    "regional_pest_watch": ["Tomato Spotted Wilt Virus", "Harlequin Bugs in late summer"]
  },
  "SD": {
    "state_name": "South Dakota",
    "extension_service": "SDSU Extension",
    "dominant_soil": "Houdek Silt Loam (South Dakota State Soil - Glacial Loess)",
    "soil_texture": "Deep Rich Prairie Silt Loam",
    "ph_range": "6.5 - 7.5 (Neutral)",
    "organic_matter": "High to Very High (4.0% - 6.0%)",
    "soil_guidance": "Fertile prairie topsoil with great nutrient density. Straw mulching buffers strong Great Plains summer winds.",
    "raised_bed_recommendation": "Raised beds warm frozen spring ground quickly and facilitate wind netting for young cucumber and squash seedlings.",
    "regional_cultivars": {"tomato": ["South Dakota Heirloom", "Early Girl", "Stupice"], "sunflower": ["Pioneer Giant", "Mammoth Russian"]},
    "regional_pest_watch": ["Grasshoppers in late July", "Flea Beetles on young greens"]
  },
  "TN": {
    "state_name": "Tennessee",
    "extension_service": "UT Extension (University of Tennessee)",
    "dominant_soil": "Dickson Silt Loam & Cumberland Valley Limestone Loam",
    "soil_texture": "Deep Silt Loam over limestone residuum",
    "ph_range": "5.8 - 6.6 (Near Neutral)",
    "organic_matter": "Moderate to High (3.0% - 4.2%)",
    "soil_guidance": "Tennessee's temperate climate supports long, productive growing seasons from April through November.",
    "raised_bed_recommendation": "Raised beds filled with rich compost and perlite prevent crusting during heavy thunderstorm downpours.",
    "regional_cultivars": {"tomato": ["Tennessee Heirloom", "Cherokee Purple (TN Heritage)", "Mountain Spring"], "beans": ["Tennessee Green Pod"]},
    "regional_pest_watch": ["Stink Bugs", "Tomato Hornworm in August"]
  },
  "TX": {
    "state_name": "Texas",
    "extension_service": "Texas A&M AgriLife Extension",
    "dominant_soil": "Houston Black Clay (Blackland Prairie) & Sandy Loam",
    "soil_texture": "Dense Gumbo Clay (Vertisols) & Coastal Sandy Loam",
    "ph_range": "6.8 - 8.2 (Alkaline in central/west; acidic in east piney woods)",
    "organic_matter": "Moderate (2.0% - 3.5%)",
    "soil_guidance": "Texas Blackland Gumbo clay expands when wet and cracks when dry. Heavy compost and expanded shale amendments improve soil tilth.",
    "raised_bed_recommendation": "Raised beds are virtually essential in heavy Texas clay to provide optimal root depth, drainage, and drip watering.",
    "regional_cultivars": {"tomato": ["Tycoon (Texas Superstar)", "Celebrity", "Solar Fire"], "peppers": ["TAM Mild Jalapeño (TAMU Bred)", "Serrano", "Habanero"]},
    "regional_pest_watch": ["Spider Mites in July dry heat", "Squash Vine Borer (plant early in March)"]
  },
  "UT": {
    "state_name": "Utah",
    "extension_service": "Utah State University (USU) Extension",
    "dominant_soil": "Manti Silt Loam & Great Basin Alluvium",
    "soil_texture": "Arid Silt Loam with high mineral calcium",
    "ph_range": "7.5 - 8.4 (Alkaline)",
    "organic_matter": "Low to Moderate (1.5% - 2.5%)",
    "soil_guidance": "Alkaline high-desert soils benefit from sulfur and liberal organic matter. Water with drip irrigation to prevent mineral crusting.",
    "raised_bed_recommendation": "Raised beds with custom peat and compost blends bypass alkaline subsoil and protect crops from cold mountain nights.",
    "regional_cultivars": {"tomato": ["Early Girl", "Celebrity", "Sun Gold"], "melon": ["Green River Cantaloupe", "Crimson Sweet"]},
    "regional_pest_watch": ["Squash Bug (use boards as overnight traps)", "Spider Mites in dry August"]
  },
  "VT": {
    "state_name": "Vermont",
    "extension_service": "UVM Extension (University of Vermont)",
    "dominant_soil": "Tunbridge-Lyman Silt Loam (Green Mountain Glacial Till)",
    "soil_texture": "Glacial Sandy Loam & Valley Silt Loam",
    "ph_range": "5.0 - 6.0 (Acidic)",
    "organic_matter": "High (4.5% - 6.5%)",
    "soil_guidance": "Cold New England mountain winters require early indoor seed starting and row covers to jumpstart June growth.",
    "raised_bed_recommendation": "Raised beds warm early in spring and provide deep, loose topsoil for heirloom root vegetables and nightshades.",
    "regional_cultivars": {"tomato": ["Stupice", "Moskvich", "Brandywine"], "squash": ["Long Pie Pumpkin (VT Heritage)", "Delicata"], "kale": ["Lacinato", "Winterbor"]},
    "regional_pest_watch": ["Flea Beetles on spring brassicas", "Late Blight in wet Augusts"]
  },
  "VA": {
    "state_name": "Virginia",
    "extension_service": "Virginia Cooperative Extension (Virginia Tech & VSU)",
    "dominant_soil": "Frederick & Davidson Silt Loam (Blue Ridge) & Manor Piedmont Loam",
    "soil_texture": "Limestone-buffered Red Clay Loam & Coastal Sandy Loam",
    "ph_range": "5.8 - 6.8 (Limestone buffered to neutral)",
    "organic_matter": "Moderate to High (3.2% - 4.5%)",
    "soil_guidance": "Rich mineral profile derived from ancient Blue Ridge limestone. Autumn season allows a complete second harvest of greens and brassicas.",
    "raised_bed_recommendation": "Terraced raised beds along rolling terrain prevent runoff and create deep, loose root zones for tomatoes and root crops.",
    "regional_cultivars": {"tomato": ["Cherokee Purple (VA Heritage)", "Celebrity", "Better Boy", "Sun Gold"], "peppers": ["Carmen", "Sweet Banana", "Habanero"]},
    "regional_pest_watch": ["Stink Bugs & Harlequin Bugs (inspect leaf undersides)", "Bacterial Wilt from Cucumber Beetles"]
  },
  "WA": {
    "state_name": "Washington",
    "extension_service": "WSU Extension (Washington State University)",
    "dominant_soil": "Tokul Gravelly Loam (Western WA) & Walla Walla Silt Loam (Eastern WA)",
    "soil_texture": "Rich Volcanic Ash Silt Loam & Glacial Till",
    "ph_range": "5.5 - 6.8 (Acidic in west; neutral in east)",
    "organic_matter": "High (4.0% - 6.5%)",
    "soil_guidance": "Western WA maritime climate requires blight-resistant nightshades; Eastern WA volcanic soils produce astounding melons and sweet onions.",
    "raised_bed_recommendation": "Raised beds elevate soil temps in cloudy spring weather and prevent root rot during rainy winter/spring cycles.",
    "regional_cultivars": {"tomato": ["Legend (WSU Bred Blight Resistant)", "Siletz", "Sun Gold"], "onion": ["Walla Walla Sweet Onion (WA Heritage)"], "berries": ["Tulameen Raspberry"]},
    "regional_pest_watch": ["Slugs in Western WA", "Late Blight on tomato foliage"]
  },
  "WV": {
    "state_name": "West Virginia",
    "extension_service": "WVU Extension Service",
    "dominant_soil": "Monongahela Silt Loam (Appalachian Plateau Uplands)",
    "soil_texture": "Deep Appalachian Silt Loam over shale residuum",
    "ph_range": "5.2 - 6.2 (Acidic)",
    "organic_matter": "Moderate to High (3.2% - 4.8%)",
    "soil_guidance": "Mountain valley soils are rich in minerals. Incorporate agricultural lime and aged compost to optimize soil pH.",
    "raised_bed_recommendation": "Terraced raised beds prevent mountain slope erosion and maximize morning sun exposure.",
    "regional_cultivars": {"tomato": ["Mortgage Lifter (WV Heritage Classic)", "Mountain Pride", "Cherokee Purple"], "beans": ["Half Runner Bean"]},
    "regional_pest_watch": ["Mexican Bean Beetle", "Tomato Hornworm in late summer"]
  },
  "WI": {
    "state_name": "Wisconsin",
    "extension_service": "UW-Madison Division of Extension",
    "dominant_soil": "Antigo Silt Loam (Wisconsin State Soil - Glacial Loess)",
    "soil_texture": "Deep Fertile Loess Silt Loam over gravelly outwash",
    "ph_range": "6.0 - 6.8 (Neutral)",
    "organic_matter": "High (3.8% - 5.5%)",
    "soil_guidance": "Famous dairy state organic matter gives Wisconsin soils wonderful moisture and fertility reserves.",
    "raised_bed_recommendation": "Raised beds thaw out quickly in late April, allowing early direct-seeding of peas, spinach, and carrots.",
    "regional_cultivars": {"tomato": ["Wisconsin 55 (UW Bred)", "Early Girl", "Brandywine"], "cranberry": ["Stevens"], "cabbage": ["Wisconsin All Seasons"]},
    "regional_pest_watch": ["Flea Beetles in May", "Squash Vine Borer in July"]
  },
  "WY": {
    "state_name": "Wyoming",
    "extension_service": "University of Wyoming Extension (Barnyards & Backyards)",
    "dominant_soil": "Forkwood Silt Loam (High Plains & Intermountain Soils)",
    "soil_texture": "Arid Silt Loam & Gravelly Loam",
    "ph_range": "7.2 - 8.2 (Alkaline)",
    "organic_matter": "Low to Moderate (1.5% - 2.8%)",
    "soil_guidance": "High elevation short growing seasons (90-120 days). Cold nights mean low hoops, frost blankets, and raised beds are essential.",
    "raised_bed_recommendation": "Raised beds warm up 3 weeks ahead of frozen ground and make wind screening simple during gusty spring days.",
    "regional_cultivars": {"tomato": ["Glacier", "Sub-Arctic Plenty", "Stupice", "Siberian"], "greens": ["Winterbor Kale", "Spinach", "Radish"]},
    "regional_pest_watch": ["Grasshoppers in mid-summer", "Cutworms in spring"]
  }
}

output_path = Path(__file__).resolve().parent.parent / "data" / "state_extensions.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(STATE_EXTENSIONS_DATA, f, indent=2)

print(f"✓ Populated 50-State Extension Knowledgebase ({len(STATE_EXTENSIONS_DATA)} states).")
